version: '3'

networks:
  mongonetwork:
    driver: bridge
  zeromqnetwork:
    driver: bridge

services:
  mongodb:
    container_name: ${PROJECT_NAME}_mongodb                   # название контейнера
    build:
      context: ./                       # имя образа
      dockerfile: mongodb.Dockerfile
                                       # перезапуск если остановлено
    environment:                                              # переменные окружения
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASS}
      MONGODB_DATA_DIR: ${MONGODB_DATA_DIR}
      MONDODB_LOG_DIR: ${MONDODB_LOG_DIR}
    volumes:                                                  # то что сохраняется после рестарта
      - ./docker/mongodb/data:${MONGODB_DATA_DIR}
      - ./docker/logs/mongodb:${MONDODB_LOG_DIR}
    networks:
      - mongonetwork
  webmongo:
    container_name: ${PROJECT_NAME}_webmongo
    image: mongo-express
    networks:
      - mongonetwork
    ports:
    - 8081:8081
    environment:                                              # переменные окружения
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_ROOT_NAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_ROOT_PASS}
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '123'
    depends_on:
      - mongodb
  php_data_collector:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_php_data_collector
    working_dir: /app
    volumes:
      - ./app:${PHP_DATA_COLLECTOR_APP_DIR}:rw
    networks:
      - mongonetwork
      - zeromqnetwork
    depends_on:
      - webmongo
  miniconda:
    container_name: miniconda
    hostname: miniconda
    image: continuumio/miniconda3
    command: /bin/bash -c "pip install pymongo && /opt/conda/bin/conda install jupyter -y --quiet && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser  --allow-root"
    ports:
      - 8888:8888
    env_file:
      - miniconda-docker-compose.env
    volumes:
      - ./notebooks:/opt/notebooks
    networks:
      - mongonetwork
